name: Deploy Frontend
on:
  push:
    branches:
      - master # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Login to Docker Hub
      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build and tag with unique version
      - name: Generate timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create unique version label
        run: echo "VERSION_LABEL=${TIMESTAMP}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Build and push Docker image
      - run: docker build --build-arg NODE_VERSION=24.2.0 -t pundeepak/react-ui:${{ env.VERSION_LABEL }} -f Dockerfile.dev .
      - run: docker push pundeepak/react-ui:${{ env.VERSION_LABEL }}

      # Run tests
      - run: docker run -e CI=true pundeepak/react-ui:${{ env.VERSION_LABEL }} npm run coverage
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: ${{ secrets.EXISTING_BUKET_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          use_existing_version_if_available: true
